# syntax=docker/dockerfile:1

FROM rust:1.97.1-slim-bookworm AS builder

WORKDIR /logos-blockchain-testing
COPY --from=logos_blockchain_testing . /logos-blockchain-testing

RUN apt-get update && apt-get install -yq \
    git gcc g++ clang libssl-dev pkg-config ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*

RUN cargo build --locked --release \
    -p cfgsync-runtime \
    --bins

FROM debian:bookworm-slim AS base

RUN apt-get update && apt-get install -yq \
    libstdc++6 libssl3 ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /logos-blockchain-testing/target/release/cfgsync-server /usr/bin/cfgsync-server
COPY --from=builder /logos-blockchain-testing/target/release/cfgsync-client /usr/bin/cfgsync-client

ENTRYPOINT ["/usr/bin/cfgsync-server"]
