[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-blockchain-config"
publish     = false
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[lints]
workspace = true

[features]
testing = ["lb-node/testing"]

[dependencies]
hex                              = { workspace = true }
lb-codec                         = { workspace = true }
lb-core                          = { workspace = true }
lb-cryptarchia-engine            = { workspace = true }
lb-groth16                       = { workspace = true }
lb-key-management-system-service = { workspace = true }
lb-libp2p                        = { workspace = true }
lb-node                          = { workspace = true }
lb-tracing                       = { workspace = true }
lb-utils                         = { workspace = true }
num-bigint                       = { workspace = true }
rand                             = { workspace = true }
time                             = { workspace = true }
