[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-blockchain-blake2btree"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[dependencies]
blake2            = { workspace = true }
lb-dynamic-merkle = { workspace = true }
lb-merkle-tree    = { workspace = true }

[dev-dependencies]
quickcheck        = { workspace = true }
quickcheck_macros = { workspace = true }
rand              = { features = ["std", "std_rng"], workspace = true }
serde             = { features = ["derive"], workspace = true }

[lints]
workspace = true
