use core::{
    fmt::Debug,
    iter::repeat_with,
    ops::{Deref, DerefMut},
};
use std::time::Duration;

use lb_blend_message::{
    MessageIdentifier, PayloadType,
    crypto::{key_ext::Ed25519SecretKeyExt as _, proofs::PoQVerificationInputsMinusSigningKey},
    encap::{ProofsVerifier, validated::EncapsulatedMessageWithVerifiedPublicHeader},
    input::EncapsulationInput,
};
use lb_blend_proofs::{
    quota::{ProofOfQuota, VerifiedProofOfQuota},
    selection::{ProofOfSelection, VerifiedProofOfSelection, inputs::VerifyInputs},
};
use lb_blend_scheduling::message_blend::provers::BlendLayerProof;
use lb_cryptarchia_engine::Epoch;
use lb_key_management_system_keys::keys::{
    Ed25519PublicKey, Ed25519Signature, UnsecuredEd25519Key,
};
use lb_libp2p::{NetworkBehaviour, ed25519, upgrade::Version};
use libp2p::{
    PeerId, StreamProtocol, Swarm, Transport as _, core::transport::MemoryTransport,
    identity::PublicKey, plaintext, swarm, tcp, yamux,
};
use libp2p_swarm_test::SwarmExt as _;

pub const PROTOCOL_NAME: StreamProtocol = StreamProtocol::new("/blend/core-behaviour/test");

/// A `PoQ` verifier for the behaviour tests, which either accepts or rejects
/// every proof it is handed. The proof system itself is exercised elsewhere;
/// here we only care about what a behaviour does with the verification outcome.
#[derive(Debug, Clone, Copy)]
pub struct TestProofsVerifier {
    accepts: bool,
}

impl TestProofsVerifier {
    pub const fn accepting() -> Self {
        Self { accepts: true }
    }

    pub const fn rejecting() -> Self {
        Self { accepts: false }
    }
}

impl ProofsVerifier for TestProofsVerifier {
    type Error = ();

    fn new(_public_inputs: PoQVerificationInputsMinusSigningKey) -> Self {
        Self::accepting()
    }

    fn verify_proof_of_quota(
        &self,
        proof: ProofOfQuota,
        _signing_key: &Ed25519PublicKey,
    ) -> Result<VerifiedProofOfQuota, Self::Error> {
        self.accepts
            .then(|| VerifiedProofOfQuota::from_proof_of_quota_unchecked(proof))
            .ok_or(())
    }

    fn verify_proof_of_selection(
        &self,
        proof: ProofOfSelection,
        _inputs: &VerifyInputs,
    ) -> Result<VerifiedProofOfSelection, Self::Error> {
        self.accepts
            .then(|| VerifiedProofOfSelection::from_proof_of_selection_unchecked(proof))
            .ok_or(())
    }
}

/// `ß_max` used by the test messages, matching the `BehaviourBuilder` default.
const NUM_BLEND_LAYERS: u64 = 3;

pub struct TestSwarm<Behaviour>(Swarm<Behaviour>)
where
    Behaviour: NetworkBehaviour;

impl<Behaviour> TestSwarm<Behaviour>
where
    Behaviour: NetworkBehaviour<ToSwarm: Debug> + Send,
{
    /// Creates [`TestSwarm`] with an ephemeral ed25519 keypair generated
    /// randomly.
    pub fn new_ephemeral<BehaviourConstructor>(behaviour_fn: BehaviourConstructor) -> Self
    where
        BehaviourConstructor: FnOnce(&ed25519::Keypair) -> Behaviour,
    {
        Self(Swarm::new_ephemeral_tokio(|identity| {
            behaviour_fn(
                &identity
                    .try_into_ed25519()
                    .expect("The identity generated by libp2p must be ed25519"),
            )
        }))
    }

    /// Creates [`TestSwarm`] with a specific [`Keypair`].
    pub fn new<BehaviourConstructor>(
        identity: &ed25519::Keypair,
        behaviour_fn: BehaviourConstructor,
    ) -> Self
    where
        BehaviourConstructor: FnOnce(&ed25519::Keypair) -> Behaviour,
    {
        let peer_id = PeerId::from(PublicKey::from(identity.public()));
        // Use TCP and Yamus to be compatible with [`Swarm::new_ephemeral_tokio`].
        let transport = MemoryTransport::default()
            .or_transport(tcp::tokio::Transport::default())
            .upgrade(Version::V1)
            .authenticate(plaintext::Config::new(&identity.clone().into()))
            .multiplex(yamux::Config::default())
            .timeout(Duration::from_secs(20))
            .boxed();

        Self(Swarm::new(
            transport,
            behaviour_fn(identity),
            peer_id,
            swarm::Config::with_tokio_executor(),
        ))
    }
}

impl<Behaviour> Deref for TestSwarm<Behaviour>
where
    Behaviour: NetworkBehaviour,
{
    type Target = Swarm<Behaviour>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<Behaviour> DerefMut for TestSwarm<Behaviour>
where
    Behaviour: NetworkBehaviour,
{
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

#[derive(Clone)]
pub struct TestEncapsulatedMessage(EncapsulatedMessageWithVerifiedPublicHeader);

impl TestEncapsulatedMessage {
    pub fn new(payload: &[u8]) -> Self {
        Self(
            EncapsulatedMessageWithVerifiedPublicHeader::try_new(
                &generate_valid_inputs(0.into()),
                PayloadType::Data,
                payload.try_into().unwrap(),
                NUM_BLEND_LAYERS.try_into().unwrap(),
            )
            .unwrap(),
        )
    }

    pub fn new_with_invalid_signature(payload: &[u8]) -> Self {
        let mut self_instance = Self::new(payload);
        *self_instance.0.public_header_mut().signature_mut() = Ed25519Signature::from([100u8; _]);
        self_instance
    }

    pub fn into_inner(self) -> EncapsulatedMessageWithVerifiedPublicHeader {
        self.0
    }

    pub fn id(&self) -> MessageIdentifier {
        self.0.id()
    }
}

impl AsRef<EncapsulatedMessageWithVerifiedPublicHeader> for TestEncapsulatedMessage {
    fn as_ref(&self) -> &EncapsulatedMessageWithVerifiedPublicHeader {
        &self.0
    }
}

pub struct TestEncapsulatedMessageWithEpoch(EncapsulatedMessageWithVerifiedPublicHeader);

impl TestEncapsulatedMessageWithEpoch {
    pub fn new(epoch: Epoch, payload: &[u8]) -> Self {
        Self(
            EncapsulatedMessageWithVerifiedPublicHeader::try_new(
                &generate_valid_inputs(epoch),
                PayloadType::Data,
                payload.try_into().unwrap(),
                NUM_BLEND_LAYERS.try_into().unwrap(),
            )
            .unwrap(),
        )
    }
}

impl Deref for TestEncapsulatedMessageWithEpoch {
    type Target = EncapsulatedMessageWithVerifiedPublicHeader;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

fn generate_valid_inputs(epoch: Epoch) -> Vec<EncapsulationInput> {
    repeat_with(UnsecuredEd25519Key::generate_with_blake_rng)
        .take(NUM_BLEND_LAYERS as usize)
        .map(|recipient_signing_key| {
            let proofs = epoch_based_mock_blend_proof(epoch);
            EncapsulationInput::try_new(
                UnsecuredEd25519Key::generate_with_blake_rng(),
                &recipient_signing_key.public_key(),
                proofs.proof_of_quota,
                proofs.proof_of_selection,
            )
            .unwrap()
        })
        .collect::<Vec<_>>()
}

fn epoch_based_mock_blend_proof(epoch: Epoch) -> BlendLayerProof {
    let epoch_bytes = epoch.into_inner().to_le_bytes();
    BlendLayerProof {
        proof_of_quota: VerifiedProofOfQuota::from_bytes_unchecked({
            let mut bytes = [0u8; _];
            bytes[..epoch_bytes.len()].copy_from_slice(&epoch_bytes);
            bytes
        }),
        proof_of_selection: VerifiedProofOfSelection::from_bytes_unchecked({
            let mut bytes = [0u8; _];
            bytes[..epoch_bytes.len()].copy_from_slice(&epoch_bytes);
            bytes
        }),
        ephemeral_signing_key: UnsecuredEd25519Key::generate_with_blake_rng(),
    }
}
