name: "Install Risc0"

description: "Install the Risc0 toolchain. Requires the Rust toolchain to be installed."

inputs:
  github_token:
    description: "The GitHub token to use for rate limiting."
    required: true

runs:
  using: "composite"
  steps:
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@b9bf4400702f721d469eec4d280125f650c85638 # Version 1.12.2
      env:
        # Required to avoid throttling by GitHub
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Install risc0 using cargo-install
      # rzup manage risc0 rust toolchain. To check what are supported versions
      # visit https://github.com/risc0/risc0 and https://github.com/risc0/rust
      # release pages.
      #
      # When updating rzup, risczero or risc0 rust toolchain also update these files:
      # * Dockerfile
      # * ci/Dockerfile
      # * testnet/Dockerfile
      # * .github/workflows/code-check.yml (the `risc0-clippy` within the `lints` job)
      run: |
        cargo install rzup --version 0.4.1 --locked \
          && ~/.cargo/bin/rzup install cargo-risczero 2.1.0 \
          && ~/.cargo/bin/rzup install rust 1.85.0
      shell: bash
      env:
        # Required to avoid throttling by GitHub
        GITHUB_TOKEN: ${{ inputs.github_token }}
