[package]
description          = "Logos blockchain test-framework integration crate"
edition.workspace    = true
license.workspace    = true
name                 = "testing-framework"
publish              = false
readme.workspace     = true
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow                           = { workspace = true }
async-trait                      = { workspace = true }
cfgsync-adapter                  = { workspace = true }
cfgsync-artifacts                = { workspace = true }
common-http-client               = { workspace = true }
flate2                           = { features = ["rust_backend"], workspace = true }
futures                          = { workspace = true }
hex                              = { workspace = true }
lb-blend-service                 = { workspace = true }
lb-chain-leader-service          = { workspace = true }
lb-chain-network-service         = { workspace = true }
lb-chain-service                 = { workspace = true }
lb-config                        = { features = ["testing"], workspace = true }
lb-core                          = { workspace = true }
lb-cryptarchia-engine            = { workspace = true }
lb-cryptarchia-sync              = { workspace = true }
lb-groth16                       = { workspace = true }
lb-http-api-common               = { workspace = true }
lb-key-management-system-service = { workspace = true }
lb-ledger                        = { workspace = true }
lb-libp2p                        = { workspace = true }
lb-network-service               = { workspace = true }
lb-node                          = { features = ["testing"], workspace = true }
lb-time-service                  = { workspace = true }
lb-tx-service                    = { workspace = true }
lb-utils                         = { workspace = true }
num-bigint                       = { workspace = true }
rand                             = { workspace = true }
reqwest                          = { features = ["json"], workspace = true }
serde                            = { workspace = true }
serde_json                       = { workspace = true }
serde_yaml                       = { workspace = true }
sysinfo                          = { features = ["disk", "system"], workspace = true }
tar                              = { workspace = true }
tempfile                         = { workspace = true }
testing-framework-core           = { workspace = true }
testing-framework-runner-compose = { workspace = true }
testing-framework-runner-k8s     = { workspace = true }
testing-framework-runner-local   = { workspace = true }
thiserror                        = { workspace = true }
time                             = { workspace = true }
tokio                            = { features = ["macros", "process", "rt-multi-thread", "time"], workspace = true }
tracing                          = { workspace = true }
uuid                             = { workspace = true }

[package.metadata.cargo-machete]
ignored = [
  "lb-blend-service",
  "lb-chain-leader-service",
  "lb-chain-network-service",
  "lb-cryptarchia-engine",
  "lb-cryptarchia-sync",
  "lb-groth16",
  "lb-ledger",
  "lb-time-service",
  "lb-utils",
  "serde_json",
]
