[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-blockchain-codec"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[lints]
workspace = true

[dependencies]
hex             = { features = ["alloc"], workspace = true }
lb-codec-macros = { workspace = true }
lb-groth16      = { workspace = true }
lb-utils        = { workspace = true }
thiserror       = { workspace = true }
