use bytes::Bytes;
use serde::{Deserialize, Serialize};

use crate::{
    codec::{DeserializeOp as _, SerializeOp as _},
    crypto::Hash,
    mantle::{
        NoteId, Utxo, Value,
        ledger::BoundedInputs,
        ops::{
            channel::{ChannelId, deposit::Metadata},
            leader_claim::VoucherNullifier,
        },
        transactions::hash::TxHash,
    },
    sdp::{DeclarationId, ServiceType},
};

/// Events generated by the execution of block/transaction/operation
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Events(Vec<Event>);

impl Events {
    #[must_use]
    pub const fn new() -> Self {
        Self(Vec::new())
    }

    pub fn extend(&mut self, events: Self) {
        self.0.extend(events.0);
    }

    pub fn iter(&self) -> impl Iterator<Item = &Event> {
        self.0.iter()
    }

    #[must_use]
    pub const fn len(&self) -> usize {
        self.0.len()
    }

    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl FromIterator<Event> for Events {
    fn from_iter<T: IntoIterator<Item = Event>>(iter: T) -> Self {
        Self(iter.into_iter().collect())
    }
}

impl From<Event> for Events {
    fn from(event: Event) -> Self {
        Self(vec![event])
    }
}

/// An event generated by the execution of block/transaction/operation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Event {
    /// Emitted while processing a block header
    Header(HeaderEvent),
    /// Emitted while processing a transaction
    Tx(TxEvent),
}

impl From<TxEvent> for Event {
    fn from(event: TxEvent) -> Self {
        Self::Tx(event)
    }
}

impl From<HeaderEvent> for Event {
    fn from(event: HeaderEvent) -> Self {
        Self::Header(event)
    }
}

/// An event emitted while processing a transaction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TxEvent {
    pub tx_hash: TxHash,
    pub op_id: Hash,
    pub payload: TxEventPayload,
}

impl TxEvent {
    #[must_use]
    pub const fn new(tx_hash: TxHash, op_id: Hash, payload: TxEventPayload) -> Self {
        Self {
            tx_hash,
            op_id,
            payload,
        }
    }
}

// A deposit re-creates one channel note per input, so the notes it emits carry
// the same bound as its inputs.
pub type DepositRecreatedNotes = BoundedInputs;

/// Event payloads emitted while processing a transaction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TxEventPayload {
    Deposit {
        channel_id: ChannelId,
        amount: Value,
        metadata: Metadata,
        /// The channel notes the deposit re-created its inputs as. They carry
        /// new `NoteId`s, so a channel cannot derive them from the payload.
        notes: DepositRecreatedNotes,
    },
    /// A leader claim operation created the reward note for its beneficiary.
    LeaderRewardClaimed {
        voucher_nullifier: VoucherNullifier,
        utxo: Utxo,
    },
}

/// Events emitted while processing a block header
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum HeaderEvent {
    /// An SDP-locked note has been unlocked because its declaration's
    /// `withdraw_at` epoch has been reached.
    SdpNoteUnlocked {
        note_id: NoteId,
        service_type: ServiceType,
        declaration_id: DeclarationId,
    },
    /// A reward UTXO was minted to a provider.
    SdpRewardDistributed {
        service_type: ServiceType,
        utxo: Utxo,
    },
}

impl TryFrom<Bytes> for Events {
    type Error = crate::codec::Error;

    fn try_from(bytes: Bytes) -> Result<Self, Self::Error> {
        Self::from_bytes(&bytes)
    }
}

impl TryFrom<Events> for Bytes {
    type Error = crate::codec::Error;

    fn try_from(events: Events) -> Result<Self, Self::Error> {
        events.to_bytes()
    }
}
