name: Docker Build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@afeb29a6e0d7d6258844ecabe6eba67d13443680  # Version 3.1.0
      - name: Build Docker Image
        uses: docker/build-push-action@84ad562665bb303b549fec655d1b64f9945f3f91  # Version 6.15.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
